defaults:
    - base
    - _self_

actor:
  rollout_policy: pipelinerl.domains.math.generate_math_rollout
  system_prompt: Please reason step by step, and put your final answer within \boxed{}.
  task_template: |-
    {task}
environment:
  _target_: pipelinerl.domains.math.MathEnvironment
dataset_loader: pipelinerl.domains.math.load_datasets

finetune:
  seq_length: 18000

vllm_config:
  vllm_kwargs:
    max_model_len: 18000

llm:
  parameters: 
    max_tokens: 16000

test_llm:
  parameters: 
    max_tokens: 16000

train_dataset_names:
- open_reasoner_zero_57k
- open_reasoner_zero_extended_72k 
test_dataset_names:
  - aime_2024
  - amc_2023
  - math_500
